name: smartBiz
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1  
 
environment:
  sdk: ">=1.12.13 <3.0.0" 
  
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  carousel_slider: ^2.3.1
  line_icons: ^0.2.0
  http: ^0.12.0+4
  json_annotation: ^2.0.0
  image_picker: ^0.6.4
  shared_preferences: ^0.5.7+2 
  shimmer: ^1.0.0
  fluttertoast: ^3.1.0
   

dev_dependencies:
  flutter_test:
    sdk: flutter

 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #    - assets/logo.png
  assets:
      - assets/logo.png      
      - assets/login_bg_b.jpg
      - assets/favorite2x.png
      - assets/shopping-bag2x.png
      - assets/menuIcon.png
      - assets/img1.jpg
      - assets/img2.jpg
      - assets/img3.jpg
      - assets/banner1.jpg
      - assets/demobanner.jpg
      - assets/pro1.jpg
      - assets/pro2.jpg
      - assets/pro3.jpg
      - assets/pro4.jpg
      - assets/pro5.jpg
      - assets/pro6.jpg
      - assets/pro7.jpg
      - assets/pro8.jpg
      - assets/pro9.jpg
      - assets/pro10.jpg
      - assets/pro11.jpg
      - assets/pro12.jpg
      - assets/pro13.jpg
      - assets/pro14.jpg
      - assets/error.png
      - assets/banners1.jpg
      - assets/banners2.jpg

      - assets/user.png
      - assets/right-arrow.png
      - assets/icon1.png
      - assets/icon2.png
      - assets/icon3.png
      - assets/icon4.png
      - assets/icon5.png
      - assets/icon6.png
      - assets/icon7.png
      - assets/icon8.png
      - assets/icon9.png
      - assets/icon10.png
      - assets/icon11.png
      - assets/icon12.png
      - assets/icon13.png

      - assets/brand1.jpg
      - assets/brand2.jpg

      - assets/offer1.jpg
      - assets/offer2.jpg
      - assets/offer3.jpg
      - assets/offer4.jpg
      - assets/detailsImg.jpg
      - assets/sucess-pic.png
      - assets/delivery-package.png
      - assets/online-store-cart.png
      - assets/icon.png
      - assets/fb.png
      - assets/gogg.png
      - assets/img_empty_cart.png
      - assets/shop.png
      - assets/blog.png
      - assets/dollar.png
      - assets/info.png
      - assets/link.png
      - assets/filter.png
      - assets/sort.png
      
      


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Montserrat
     fonts:
       - asset: fonts/Montserrat-Regular.ttf
         weight: 400
       - asset: fonts/Montserrat-Light.ttf
         weight: 300
       - asset: fonts/Montserrat-Medium.ttf
         weight: 500
       - asset: fonts/Montserrat-SemiBold.ttf
         weight: 600
       - asset: fonts/Montserrat-Bold.ttf
         weight: 800
       - asset: fonts/Montserrat-Black.ttf
         weight: 900
  #  - family: Trajan Pro
  #    fonts:
  #      - asset: fonts/TrajanPro.ttf
  #      - asset: fonts/TrajanPro_Bold.ttf
  #        weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
